// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HexToFloat
{
    
    #region Windows Form Designer generated code
    public partial class MainForm
    {
        private void InitializeComponent()
        {
            this.resultBox = new System.Windows.Forms.TextBox();
            this.buttonConvert = new System.Windows.Forms.Button();
            this.sourceBox = new System.Windows.Forms.TextBox();
            this.hexToFloat = new System.Windows.Forms.RadioButton();
            this.floatToHex = new System.Windows.Forms.RadioButton();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.littleEndianButton = new System.Windows.Forms.RadioButton();
            this.bigEndianButton = new System.Windows.Forms.RadioButton();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.singlePrecision = new System.Windows.Forms.RadioButton();
            this.doublePrecision = new System.Windows.Forms.RadioButton();
            this.checkBoxSpaces = new System.Windows.Forms.CheckBox();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            // 
            // resultBox
            // 
            this.resultBox.Text = "";
            this.resultBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.resultBox.ReadOnly = true;
            this.resultBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.resultBox.Location = new System.Drawing.Point(12, 118);
            this.resultBox.Name = "resultBox";
            this.resultBox.Size = new System.Drawing.Size(372, 26);
            this.resultBox.TabIndex = 1;
            // 
            // buttonConvert
            // 
            this.buttonConvert.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.buttonConvert.Text = "Convert";
            this.buttonConvert.UseVisualStyleBackColor = true;
            this.buttonConvert.Location = new System.Drawing.Point(312, 88);
            this.buttonConvert.Name = "buttonConvert";
            this.buttonConvert.Size = new System.Drawing.Size(75, 27);
            this.buttonConvert.TabIndex = 2;
            this.buttonConvert.Click += new System.EventHandler(this.button1_Click);
            // 
            // sourceBox
            // 
            this.sourceBox.Text = "";
            this.sourceBox.BackColor = System.Drawing.SystemColors.Window;
            this.sourceBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.sourceBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sourceBox.Location = new System.Drawing.Point(12, 12);
            this.sourceBox.Name = "sourceBox";
            this.sourceBox.Size = new System.Drawing.Size(372, 26);
            this.sourceBox.TabIndex = 0;
            // 
            // hexToFloat
            // 
            this.hexToFloat.Checked = true;
            this.hexToFloat.TabStop = true;
            this.hexToFloat.AutoSize = true;
            this.hexToFloat.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.hexToFloat.Text = "Hex -> Float";
            this.hexToFloat.UseVisualStyleBackColor = true;
            this.hexToFloat.Location = new System.Drawing.Point(6, 20);
            this.hexToFloat.Name = "hexToFloat";
            this.hexToFloat.Size = new System.Drawing.Size(88, 19);
            this.hexToFloat.TabIndex = 3;
            // 
            // floatToHex
            // 
            this.floatToHex.AutoSize = true;
            this.floatToHex.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.floatToHex.Text = "Float -> Hex";
            this.floatToHex.UseVisualStyleBackColor = true;
            this.floatToHex.Location = new System.Drawing.Point(6, 45);
            this.floatToHex.Name = "floatToHex";
            this.floatToHex.Size = new System.Drawing.Size(88, 19);
            this.floatToHex.TabIndex = 4;
            // 
            // groupBox1
            // 
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Conversion type";
            this.groupBox1.Controls.Add(this.hexToFloat);
            this.groupBox1.Controls.Add(this.floatToHex);
            this.groupBox1.Location = new System.Drawing.Point(16, 43);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(99, 72);
            this.groupBox1.TabIndex = 5;
            // 
            // groupBox2
            // 
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Endianness";
            this.groupBox2.Controls.Add(this.littleEndianButton);
            this.groupBox2.Controls.Add(this.bigEndianButton);
            this.groupBox2.Location = new System.Drawing.Point(121, 43);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(99, 72);
            this.groupBox2.TabIndex = 6;
            // 
            // littleEndianButton
            // 
            this.littleEndianButton.Checked = true;
            this.littleEndianButton.TabStop = true;
            this.littleEndianButton.AutoSize = true;
            this.littleEndianButton.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.littleEndianButton.Text = "Little Endian";
            this.littleEndianButton.UseVisualStyleBackColor = true;
            this.littleEndianButton.Location = new System.Drawing.Point(6, 20);
            this.littleEndianButton.Name = "littleEndianButton";
            this.littleEndianButton.Size = new System.Drawing.Size(89, 19);
            this.littleEndianButton.TabIndex = 3;
            // 
            // bigEndianButton
            // 
            this.bigEndianButton.AutoSize = true;
            this.bigEndianButton.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.bigEndianButton.Text = "Big Endian";
            this.bigEndianButton.UseVisualStyleBackColor = true;
            this.bigEndianButton.Location = new System.Drawing.Point(6, 45);
            this.bigEndianButton.Name = "bigEndianButton";
            this.bigEndianButton.Size = new System.Drawing.Size(80, 19);
            this.bigEndianButton.TabIndex = 4;
            // 
            // groupBox3
            // 
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Precision";
            this.groupBox3.Controls.Add(this.doublePrecision);
            this.groupBox3.Controls.Add(this.singlePrecision);
            this.groupBox3.Location = new System.Drawing.Point(224, 43);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(80, 72);
            this.groupBox3.TabIndex = 7;
            // 
            // singlePrecision
            // 
            this.singlePrecision.AutoSize = true;
            this.singlePrecision.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.singlePrecision.Text = "Single";
            this.singlePrecision.UseVisualStyleBackColor = true;
            this.singlePrecision.Location = new System.Drawing.Point(8, 17);
            this.singlePrecision.Name = "singlePrecision";
            this.singlePrecision.Size = new System.Drawing.Size(58, 19);
            this.singlePrecision.TabIndex = 0;
            // 
            // doublePrecision
            // 
            this.doublePrecision.Checked = true;
            this.doublePrecision.TabStop = true;
            this.doublePrecision.AutoSize = true;
            this.doublePrecision.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.doublePrecision.Text = "Double";
            this.doublePrecision.UseVisualStyleBackColor = true;
            this.doublePrecision.Location = new System.Drawing.Point(8, 43);
            this.doublePrecision.Name = "doublePrecision";
            this.doublePrecision.Size = new System.Drawing.Size(63, 19);
            this.doublePrecision.TabIndex = 1;
            // 
            // checkBoxSpaces
            // 
            this.checkBoxSpaces.Checked = true;
            this.checkBoxSpaces.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBoxSpaces.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.checkBoxSpaces.Text = "Spaces";
            this.checkBoxSpaces.UseVisualStyleBackColor = true;
            this.checkBoxSpaces.Location = new System.Drawing.Point(312, 48);
            this.checkBoxSpaces.Name = "checkBoxSpaces";
            this.checkBoxSpaces.Size = new System.Drawing.Size(72, 24);
            this.checkBoxSpaces.TabIndex = 8;
            // 
            // MainForm
            // 
            this.AcceptButton = this.buttonConvert;
            this.ClientSize = new System.Drawing.Size(395, 155);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Text = "Hex to Float and vice versa";
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.sourceBox);
            this.Controls.Add(this.buttonConvert);
            this.Controls.Add(this.resultBox);
            this.Controls.Add(this.checkBoxSpaces);
            this.Name = "MainForm";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
        }
        private System.Windows.Forms.TextBox resultBox;
        private System.Windows.Forms.Button buttonConvert;
        private System.Windows.Forms.TextBox sourceBox;
        private System.Windows.Forms.RadioButton hexToFloat;
        private System.Windows.Forms.RadioButton floatToHex;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.RadioButton littleEndianButton;
        private System.Windows.Forms.RadioButton bigEndianButton;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.RadioButton singlePrecision;
        private System.Windows.Forms.RadioButton doublePrecision;
        private System.Windows.Forms.CheckBox checkBoxSpaces;
    }
    #endregion
}
